package com.hsbc.ce.gdt.refdata.controller;

 

import com.hsbc.ce.gdt.refdata.constant.Constants;

import com.hsbc.ce.gdt.refdata.dto.FilterDto;

import com.hsbc.ce.gdt.refdata.exception.InvalidRequestParamException;

import com.hsbc.ce.gdt.refdata.service.AuditTrailService;

import com.hsbc.ce.gdt.refdata.service.DataAssetService;

import com.hsbc.ce.gdt.refdata.service.FilterService;

import com.hsbc.ce.gdt.refdata.service.RouteService;

import com.hsbc.ce.gdt.refdata.utils.ValidationUtil;

import com.hsbc.gdt.refdata.caching.entity.Page;

import com.hsbc.gdt.refdata.caching.entity.Route;

import io.swagger.v3.oas.annotations.Parameter;

import io.swagger.v3.oas.annotations.Parameters;

import io.swagger.v3.oas.annotations.enums.ParameterIn;

import io.swagger.v3.oas.annotations.media.Schema;

import jakarta.servlet.http.HttpServletRequest;

import lombok.extern.slf4j.Slf4j;

import org.json.simple.JSONObject;

import org.springframework.beans.factory.annotation.Autowired;

import org.springframework.beans.factory.annotation.Value;

import org.springframework.data.domain.PageRequest;

import org.springframework.http.HttpHeaders;

import org.springframework.http.HttpStatus;

import org.springframework.http.ResponseEntity;

import org.springframework.web.bind.annotation.*;

 

import java.util.HashMap;

import java.util.List;

import java.util.Map;

 

import static com.hsbc.ce.gdt.refdata.utils.ValidationUtil.validateHeader;

import static com.hsbc.ce.gdt.refdata.utils.ValidationUtil.validatePageParams;

 

/**

* @author ravidas.ghodse

*/

 

@RestController

@RequestMapping("/v1")

@Slf4j

public class GenericController {

 

    private final DataAssetService dataAssetService;

    private final RouteService routeService;

    private final FilterService filterService;

    private final AuditTrailService auditTrailService;

 

    @Value("${com.hsbc.ce.gdt.refdata.default.pageSize}")

    private int defaultPageSize;

 

    @Autowired

    public GenericController(DataAssetService dataAssetService, RouteService routeService, FilterService filterService, AuditTrailService auditTrailService) {

       this.dataAssetService = dataAssetService;

       this.routeService = routeService;

       this.filterService = filterService;

       this.auditTrailService = auditTrailService;

    }

 

    /**

     * Generic controller to fetch the details of requested Data Asset(routeName)

     *

     * @param request          http://localhost:8080/{routeName}?page=0&size=100&filter1=value&filter2=value2&filter3=value3

     * @param routeName        Route name for data asset

     * @param requestParamsMap filters and pagination params

     * @return Page<JSONObject>

     */

    @GetMapping(path = {"/{routeName}"})

    @Parameters(value = {

          @Parameter(name = "X-HSBC-Chnl-CountryCode",

                description = "The country code of the channel application (or system) that was used by a customer (or member of staff) to interact with HSBC.",

                in = ParameterIn.HEADER, schema = @Schema(type = "string"), required = true, example = "UK"),

 

          @Parameter(name = "X-HSBC-Request-Correlation-Id",

                description = "- This header contains a UUID for each request that is generated by the originating client application (e.g. the web application in the example below).  " +

                      "It is cascaded through all API layers via this header to help correlate the originating request with the specific API calls made to fulfil that request.\n" +

                      "- The application that calls the API SHOULD write the UUID value and information about the API call to a log file before making the call.",

                in = ParameterIn.HEADER, schema = @Schema(type = "string"), required = true, example = "d415380f-60ee-48d1-94d4-36fdf704e58f"),

 

          @Parameter(name = "X-HSBC-Source-System-Id",

                description = "The EIM Application Instance Id of the source system (or application) at HSBC that initiates the call to an API.",

                in = ParameterIn.HEADER, schema = @Schema(type = "string"), required = true, example = "7654321"),

 

          @Parameter(name = "X-HSBC-GBGF",

                description = "The Global Business or Global Function (GBGF) as defined by the Business.  " +

                      "- There are four Global Businesses: RBWM, CMB, GPB and GBM. " +

                      "- A Global Function is a concern that cross cuts across all of the Global Businesses such as Payments or HR.",

                in = ParameterIn.HEADER, schema = @Schema(type = "string"), example = "GDT"),

 

          @Parameter(name = "X-HSBC-Src-UserAgent",

                description = "User Agent from user's machine/browser",

                in = ParameterIn.HEADER, schema = @Schema(type = "string"), hidden = true),

 

          @Parameter(name = "page", description = "Page number start with 1.", in = ParameterIn.QUERY, schema = @Schema(type = "integer")),

          @Parameter(name = "size", description = "Number of elements per page, size of requested page.", in = ParameterIn.QUERY, schema = @Schema(type = "integer")),

          @Parameter(name = "rdhLastIngestionTimestamp", description = "Last successful reconciliation timestamp (format: yyyy-MM-dd). Returns only records ingested after this timestamp. Applicable only for CORE_BANKING_COMMON_DATA_MODEL_REFERENCE_CODES data asset.", in = ParameterIn.QUERY, schema = @Schema(type = "string"), example = "2025-12-31")

    })

    public ResponseEntity<Page<JSONObject>> getDataAssets(HttpServletRequest request, @PathVariable String routeName, @RequestParam Map<String, String> requestParamsMap) {

       Page<JSONObject> data;

       validateHeader(request);

       PageRequest pageRequest = validatePageParams(defaultPageSize, requestParamsMap);

       Route route = routeService.getRoute(routeName);

       List<FilterDto> filters = filterService.getFilters(route);

      Map<String, String> requestParamsForValidation = new HashMap<>(requestParamsMap);

      requestParamsForValidation.remove("rdhLastIngestionTimestamp");

      Map<String, String> filterMap = ValidationUtil.getFilterParams(filters, requestParamsForValidation);

       auditTrailService.captureAuditTrail(route, request);

       log.info("route............>"+ route.getAssetName());

       String rdhLastIngestionTimestamp = requestParamsMap.get("rdhLastIngestionTimestamp");

       if (route.getAssetName().equals(Constants.CORE_BANKING_COMMON_DATA_MODEL_REFERENCE_CODES)) {

           if (rdhLastIngestionTimestamp != null && !rdhLastIngestionTimestamp.isEmpty()) {

                              if (!rdhLastIngestionTimestamp.matches("^\\d{4}-\\d{2}-\\d{2}$")) {

                                    throw new InvalidRequestParamException("rdhLastIngestionTimestamp should be in yyyy-MM-dd format");

                     }

               log.info("Filtering records ingested after timestamp: {}", rdhLastIngestionTimestamp);

                                          filterMap.put("rdhLastIngestionTimestamp", rdhLastIngestionTimestamp);

           }

           data = dataAssetService.getDataWithNestedParams(route, pageRequest, filterMap, filters);

       }

       else if(route.getAttributeType()!=null && route.getAttributeType().equals("MDM")){

          data = dataAssetService.getDataForMDM(route, pageRequest, filterMap);

       }

       else {

          data = dataAssetService.getData(route, pageRequest, filterMap);

       }

       HttpHeaders responseHeaders = new HttpHeaders();

       responseHeaders.set("Strict-Transport-Security", "max-age=31536000; includeSubdomains");

       return ResponseEntity.status(HttpStatus.OK).headers(responseHeaders).body(data);

    }




    @GetMapping(path = {"/search/{routeName}"})

    @Parameters(value = {

          @Parameter(name = "X-HSBC-Chnl-CountryCode",

                description = "The country code of the channel application (or system) that was used by a customer (or member of staff) to interact with HSBC.",

                in = ParameterIn.HEADER, schema = @Schema(type = "string"), required = true, example = "UK"),

 

          @Parameter(name = "X-HSBC-Request-Correlation-Id",

                description = "- This header contains a UUID for each request that is generated by the originating client application (e.g. the web application in the example below).  " +

                      "It is cascaded through all API layers via this header to help correlate the originating request with the specific API calls made to fulfil that request.\n" +

                      "- The application that calls the API SHOULD write the UUID value and information about the API call to a log file before making the call.",

                in = ParameterIn.HEADER, schema = @Schema(type = "string"), required = true, example = "d415380f-60ee-48d1-94d4-36fdf704e58f"),

 

          @Parameter(name = "X-HSBC-Source-System-Id",

                description = "The EIM Application Instance Id of the source system (or application) at HSBC that initiates the call to an API.",

                in = ParameterIn.HEADER, schema = @Schema(type = "string"), required = true, example = "7654321"),

 

          @Parameter(name = "X-HSBC-GBGF",

                description = "The Global Business or Global Function (GBGF) as defined by the Business.  " +

                      "- There are four Global Businesses: RBWM, CMB, GPB and GBM. " +

                      "- A Global Function is a concern that cross cuts across all of the Global Businesses such as Payments or HR.",

                in = ParameterIn.HEADER, schema = @Schema(type = "string"), example = "GDT"),

 

          @Parameter(name = "X-HSBC-Src-UserAgent",

                description = "User Agent from user's machine/browser",

                in = ParameterIn.HEADER, schema = @Schema(type = "string"), hidden = true),

 

          @Parameter(name = "page", description = "Page number start with 1.", in = ParameterIn.QUERY, schema = @Schema(type = "integer")),

          @Parameter(name = "size", description = "Number of elements per page, size of requested page.", in = ParameterIn.QUERY, schema = @Schema(type = "integer"))

    })

    public ResponseEntity<Page<JSONObject>> getDataAssetsWithLikeFilters(HttpServletRequest request, @PathVariable String routeName, @RequestParam Map<String, String> requestParamsMap) {

       validateHeader(request);

       PageRequest pageRequest = validatePageParams(defaultPageSize, requestParamsMap);

       Route route = routeService.getRoute(routeName);

       List<FilterDto> filters = filterService.getFilters(route);

       Map<String, String> filterMap = ValidationUtil.getFilterParams(filters, requestParamsMap);

       auditTrailService.captureAuditTrail(route, request);

       Page<JSONObject> data = dataAssetService.getSearchData(route, pageRequest, filterMap);

       HttpHeaders responseHeaders = new HttpHeaders();

       responseHeaders.set("Strict-Transport-Security", "max-age=31536000; includeSubdomains");

       return ResponseEntity.status(HttpStatus.OK).headers(responseHeaders).body(data);

 

    }

}